FROM node:20-alpine

WORKDIR /usr/src/app

# Copy package.json
COPY dashboard/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Expose port
EXPOSE 5173

CMD ["npm", "run", "dev"]
