FROM node:25-alpine

WORKDIR /usr/src/docs

COPY docs/package*.json ./
COPY docs/scripts ./scripts
COPY docs/src ./src
COPY bot/src ../bot/src
COPY shared ../shared
COPY README.md ../
COPY package*.json ../

RUN npm install
RUN npm install @rollup/rollup-linux-x64-musl

RUN npm run generate

EXPOSE 5174

CMD ["npm", "run", "dev"]